spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2demo?serverTimezone=UTC
    username: root
    password: Rjdifh_1999
  jpa:
    hibernate:
      ddl-auto: create-drop

  #spring.security.oauth2.client.registration.google.client-id=${googleClientId}
  #spring.security.oauth2.client.registration.google.client-secret=${googleClientSecret}

  #spring.security.oauth2.client.registration.github.client-id=${gitHubClientId}
  #spring.security.oauth2.client.registration.github.client-secret=${gitHubClientSecret}

google:
  client:
    clientId: ${googleClientId}
    clientSecret: ${googleClientSecret}
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope: openid,email,profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    preferTokenInfo: true

github:
  client:
    clientId: ${gitHubClientId}
    clientSecret: ${gitHubClientSecret}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    scope: read:user,user:email
  resource:
    userInfoUri: https://api.github.com/user
